import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Menu from '@/componentes/Menu';
import 'bootstrap/dist/css/bootstrap.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Loja Next',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Menu />
				{children}
			</body>
		</html>
	);
}
